5.12 - Signinig certificates via the K8s api

1 - Create a CertificatesSigningRequest
2 - Approve/deny CSR 
3 - Permission to certificates are related to RBAC, so you can decide who can approve or deny the CSR. 

### Hands-On 

Let's create CSR: 

[root@host ~]# apt-get install -y golang-cfssl

cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "tls-svc.tls-test.svc.cluster.local",
    "tls-pod.tls-test.pod.cluster.local",
    "192.0.2.24",
    "10.0.34.2"
  ],
  "CN": "system:node:tls-pod.tls-test.pod.cluster.local",
  "key": {
    "algo": "ecdsa",
    "size": 256
  },
  "names": [
    {
      "O": "system:nodes"
    }
  ]
}
EOF
[root@host cks]# ls -lrt
total 16
-rw------- 1 root root 227 Jan 31 00:56 server-key.pem
-rw-r--r-- 1 root root 590 Jan 31 00:56 server.csr

[root@host cks]# cat server.csr | base64
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmV6Q0NBU0lDQVFBd1VERVZN
Qk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWta
VHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhL
b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpP
Qk4KMElTZTF1UUhvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09x
QndNRzRHQ1NxRwpTSWIzRFFFSkRqRmhNRjh3WFFZRFZSMFJCRll3VklJaWRHeHpMWE4yWXk1MGJI
TXRkR1Z6ZEM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJSWlkR3h6TFhCdlpDNTBiSE10ZEdWemRD
NXdiMlF1WTJ4MWMzUmxjaTVzYjJOaGJJY0UKd0FBQ0dJY0VDZ0FpQWpBS0JnZ3Foa2pPUFFRREFn
TkhBREJFQWlCRktkUSt5OFNDWW1CSG1SU0ZpYllLSnhXRQpvREdvU2hMcytybm9RSjAvNlFJZ05Z
N2xTK09wanA0VGQ0UW90c1Z1YkJXYnBUY2VxbkI4UjkzN041Q0V0WHc9Ci0tLS0tRU5EIENFUlRJ
RklDQVRFIFJFUVVFU1QtLS0tLQo=

Let's create a csr: tls-svc-csr.yaml 

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
Metadata: 
  name: tls-svc-csr 
spec: 
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmV6Q0NBU0lDQVFBd1VERVZN
    Qk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWta
    VHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhL
    b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpP
    Qk4KMElTZTF1UUhvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09x
    QndNRzRHQ1NxRwpTSWIzRFFFSkRqRmhNRjh3WFFZRFZSMFJCRll3VklJaWRHeHpMWE4yWXk1MGJI
    TXRkR1Z6ZEM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJSWlkR3h6TFhCdlpDNTBiSE10ZEdWemRD
    NXdiMlF1WTJ4MWMzUmxjaTVzYjJOaGJJY0UKd0FBQ0dJY0VDZ0FpQWpBS0JnZ3Foa2pPUFFRREFn
    TkhBREJFQWlCRktkUSt5OFNDWW1CSG1SU0ZpYllLSnhXRQpvREdvU2hMcytybm9RSjAvNlFJZ05Z
    N2xTK09wanA0VGQ0UW90c1Z1YkJXYnBUY2VxbkI4UjkzN041Q0V0WHc9Ci0tLS0tRU5EIENFUlRJ
    RklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kubelet-serving 
  usages: 
  - digital signature 
  - key encipherment 
  - server auth 

[root@host cks]# k create -f tls-svc-csr.yml
certificatesigningrequest.certificates.k8s.io/tls-svc-csr created
[root@host cks]# k get csr
NAME          AGE   SIGNERNAME                      REQUESTOR          REQUESTEDDURATION   CONDITION
tls-svc-csr   20s   kubernetes.io/kubelet-serving   kubernetes-admin   <none>              Pending
[root@host cks]# k certificate approve tls-svc-csr
certificatesigningrequest.certificates.k8s.io/tls-svc-csr approved
[root@host cks]# k get csr
NAME          AGE   SIGNERNAME                      REQUESTOR          REQUESTEDDURATION   CONDITION
tls-svc-csr   49s   kubernetes.io/kubelet-serving   kubernetes-admin   <none>              Approved,Issued

[root@host cks]# k get csr tls-svc-csr -o yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2024-01-31T00:06:03Z"
  name: tls-svc-csr
  resourceVersion: "9081492"
  uid: 1eb1e1a4-d3ba-4676-a5e4-f7cdd96c3735
spec:
  groups:
  - system:masters
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmV6Q0NBU0lDQVFBd1VERVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWtaVHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpPQk4KMElTZTF1UUhvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09xQndNRzRHQ1NxRwpTSWIzRFFFSkRqRmhNRjh3WFFZRFZSMFJCRll3VklJaWRHeHpMWE4yWXk1MGJITXRkR1Z6ZEM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJSWlkR3h6TFhCdlpDNTBiSE10ZEdWemRDNXdiMlF1WTJ4MWMzUmxjaTVzYjJOaGJJY0UKd0FBQ0dJY0VDZ0FpQWpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCRktkUSt5OFNDWW1CSG1SU0ZpYllLSnhXRQpvREdvU2hMcytybm9RSjAvNlFJZ05ZN2xTK09wanA0VGQ0UW90c1Z1YkJXYnBUY2VxbkI4UjkzN041Q0V0WHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
  username: kubernetes-admin
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyekNDQWNPZ0F3SUJBZ0lRTmw2THYwSm5MNnJLTHBYR3BtZ0lxakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEkwTURFek1UQXdNREV6TWxvWERUSTFNREV6TURBdwpNREV6TWxvd1VERVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1emVYTjBaVzA2CmJtOWtaVHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3RXdZSEtvWkkKemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpPQk4wSVNlMXVRSApvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09xT0J0akNCc3pBT0JnTlZIUThCCkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBZkJnTlYKSFNNRUdEQVdnQlFMaXFDSjlaeVdKbzc0RldvaHNZY1lEdHdFN0RCZEJnTlZIUkVFVmpCVWdpSjBiSE10YzNaagpMblJzY3kxMFpYTjBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNnaUowYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2ClpDNWpiSFZ6ZEdWeUxteHZZMkZzaHdUQUFBSVlod1FLQUNJQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXIKVENxTUJqR1RnbkdldXBYbGlWNzNFWXJGQjV1YjJoQlhFQ0NPUC9JTVhoNDZkV2tlNUw2eHNGV0NPQzNlYW9MZwpRMHNQU0FYeVFSUlhmZXY0LzVPanppYTl1cUxOallRanByRXNQVFluaDBQMitiSllxQ1hTaEtQb3pJU3hoYXJiCjAxVEErZm9udDMxRlBoaUdVMXF0SStUbVpiTDlEZ0FCRlkrbUZFNEQyTlQrVGY3RlRNWFA2OGJDZVFNNnY5aGsKMWFkcVd6dWg5Um13UGszRk9SUmlCQlhvZVhqNlNaUGM4dzBPNWlFTHpJdkxJWkJ5SGtDV0JzNklJVEVsWnk5MQp6a0dDMURjUCtac0ovcWFHVHhSaDJoc0RCcVFydDRkMFhvcU5NbEh0ZlF2V0ZUL2RpWDhxS3l5Z0ZoQm5INFR5CnlGeWN6NmZTQzVWWlNmRE95ZTlMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  conditions:
  - lastTransitionTime: "2024-01-31T00:06:32Z"
    lastUpdateTime: "2024-01-31T00:06:32Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved

THEN WE HAVE OUR CERTIFICATE: 


[root@host cks]# echo LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyekNDQWNPZ0F3SUJBZ0lRTmw2THYwSm5MNnJLTHBYR3BtZ0lxakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEkwTURFek1UQXdNREV6TWxvWERUSTFNREV6TURBdwpNREV6TWxvd1VERVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1emVYTjBaVzA2CmJtOWtaVHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3RXdZSEtvWkkKemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpPQk4wSVNlMXVRSApvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09xT0J0akNCc3pBT0JnTlZIUThCCkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBZkJnTlYKSFNNRUdEQVdnQlFMaXFDSjlaeVdKbzc0RldvaHNZY1lEdHdFN0RCZEJnTlZIUkVFVmpCVWdpSjBiSE10YzNaagpMblJzY3kxMFpYTjBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNnaUowYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2ClpDNWpiSFZ6ZEdWeUxteHZZMkZzaHdUQUFBSVlod1FLQUNJQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXIKVENxTUJqR1RnbkdldXBYbGlWNzNFWXJGQjV1YjJoQlhFQ0NPUC9JTVhoNDZkV2tlNUw2eHNGV0NPQzNlYW9MZwpRMHNQU0FYeVFSUlhmZXY0LzVPanppYTl1cUxOallRanByRXNQVFluaDBQMitiSllxQ1hTaEtQb3pJU3hoYXJiCjAxVEErZm9udDMxRlBoaUdVMXF0SStUbVpiTDlEZ0FCRlkrbUZFNEQyTlQrVGY3RlRNWFA2OGJDZVFNNnY5aGsKMWFkcVd6dWg5Um13UGszRk9SUmlCQlhvZVhqNlNaUGM4dzBPNWlFTHpJdkxJWkJ5SGtDV0JzNklJVEVsWnk5MQp6a0dDMURjUCtac0ovcWFHVHhSaDJoc0RCcVFydDRkMFhvcU5NbEh0ZlF2V0ZUL2RpWDhxS3l5Z0ZoQm5INFR5CnlGeWN6NmZTQzVWWlNmRE95ZTlMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K | base64 -d
-----BEGIN CERTIFICATE-----
MIIC2zCCAcOgAwIBAgIQNl6Lv0JnL6rKLpXGpmgIqjANBgkqhkiG9w0BAQsFADAV
MRMwEQYDVQQDEwprdWJlcm5ldGVzMB4XDTI0MDEzMTAwMDEzMloXDTI1MDEzMDAw
MDEzMlowUDEVMBMGA1UEChMMc3lzdGVtOm5vZGVzMTcwNQYDVQQDEy5zeXN0ZW06
bm9kZTp0bHMtcG9kLnRscy10ZXN0LnBvZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAE9fyj+Xx1xfLyHD2pv/Jlr64uuA5MjOBN0ISe1uQH
oUmFdfnYG6VyObsBW1sADHPRU1ouBhKkgOQ5VP24u1eWOqOBtjCBszAOBgNVHQ8B
Af8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAfBgNV
HSMEGDAWgBQLiqCJ9ZyWJo74FWohsYcYDtwE7DBdBgNVHREEVjBUgiJ0bHMtc3Zj
LnRscy10ZXN0LnN2Yy5jbHVzdGVyLmxvY2FsgiJ0bHMtcG9kLnRscy10ZXN0LnBv
ZC5jbHVzdGVyLmxvY2FshwTAAAIYhwQKACICMA0GCSqGSIb3DQEBCwUAA4IBAQAr
TCqMBjGTgnGeupXliV73EYrFB5ub2hBXECCOP/IMXh46dWke5L6xsFWCOC3eaoLg
Q0sPSAXyQRRXfev4/5Ojzia9uqLNjYQjprEsPTYnh0P2+bJYqCXShKPozISxharb
01TA+font31FPhiGU1qtI+TmZbL9DgABFY+mFE4D2NT+Tf7FTMXP68bCeQM6v9hk
1adqWzuh9RmwPk3FORRiBBXoeXj6SZPc8w0O5iELzIvLIZByHkCWBs6IITElZy91
zkGC1DcP+ZsJ/qaGTxRh2hsDBqQrt4d0XoqNMlHtfQvWFT/diX8qKyygFhBnH4Ty
yFycz6fSC5VZSfDOye9L
-----END CERTIFICATE-----
