5.9 - Creating a container runtime sandbox

Gvisor gives you an emulated kernel that allows you to run untrusted wordloads. So the containers will not use the host vm kernel, but an emulated one.
Gvisor uses a runtime for the contaieners and it's called "runsc".
_________________________________________________________________________
Let's istall gVisor on all the nodes: master and workers

sudo apt-get update && \
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg

curl -fsSL https://gvisor.dev/archive.key | sudo gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" | sudo tee /etc/apt/sources.list.d/gvisor.list > /dev/null

sudo apt-get update && sudo apt-get install -y runsc

Let's configure containerd to use also runsc. Here there is a vimdiff between the modded configuration of config.toml inside the /etc/containerd dir and the config.toml.ori original file, before the mod for runsc:

root@vmi1537862:/etc/containerd# vimdiff config.toml.ori config.toml
2 files to edit
  disabled_plugins = []                                                                                |  disabled_plugins = ["io.containerd.internal.v1.restart"]
  imports = []                                                                                         |  imports = []
  oom_score = 0                                                                                        |  oom_score = 0
  plugin_dir = ""                                                                                      |  plugin_dir = ""
  required_plugins = []                                                                                |  required_plugins = []
  root = "/var/lib/containerd"                                                                         |  root = "/var/lib/containerd"
  state = "/run/containerd"                                                                            |  state = "/run/containerd"
+ +--111 lines: temp = ""------------------------------------------------------------------------------|+ +--111 lines: temp = ""-----------------------------------------------------------------------------
            runtime_engine = ""                                                                        |            runtime_engine = ""
            runtime_path = ""                                                                          |            runtime_path = ""
            runtime_root = ""                                                                          |            runtime_root = ""
            runtime_type = "io.containerd.runc.v2"                                                     |            runtime_type = "io.containerd.runc.v2"
            sandbox_mode = "podsandbox"                                                                |            sandbox_mode = "podsandbox"
            snapshotter = ""                                                                           |            snapshotter = ""
                                                                                                       |          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
  -----------------------------------------------------------------------------------------------------|            runtime_type = "io.containerd.runsc.v1"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]                     |            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              BinaryName = ""                                                                          |              BinaryName = ""
              CriuImagePath = ""                                                                       |              CriuImagePath = ""
              CriuPath = ""                                                                            |              CriuPath = ""
              CriuWorkPath = ""                                                                        |              CriuWorkPath = ""
              IoGid = 0                                                                                |              IoGid = 0
+ +-- 66 lines: IoUid = 0------------------------------------------------------------------------------|+ +-- 66 lines: IoUid = 0-----------------------------------------------------------------------------
                                                                                                       |
    [plugins."io.containerd.runtime.v1.linux"]                                                         |    [plugins."io.containerd.runtime.v1.linux"]
      no_shim = false                                                                                  |      no_shim = false
      runtime = "runc"                                                                                 |      runtime = "runc"
      runtime_root = ""                                                                                |      runtime_root = ""
      shim = "containerd-shim"                                                                         |      shim = "containerd-shim"
      shim_debug = false                                                                               |      shim_debug = true
                                                                                                       |
    [plugins."io.containerd.runtime.v2.task"]                                                          |    [plugins."io.containerd.runtime.v2.task"]
      platforms = ["linux/amd64"]                                                                      |      platforms = ["linux/amd64"]
      sched_core = false                                                                               |      sched_core = false
                                                                                                       |
    [plugins."io.containerd.service.v1.diff-service"]                                                  |    [plugins."io.containerd.service.v1.diff-service"]
+ +-- 76 lines: default = ["walking"]------------------------------------------------------------------|+ +-- 76 lines: default = ["walking"]-----------------------------------------------------------------
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
~                                                                                                      |~
config.toml.ori                                                                      1,21           All config.toml                                                                         1,21           All

_________________________________________________________________________

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runsc-sandbox
handler: runsc  

apiVersion: v1
kind: Pod
metadata:
  name: non-sandbox-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Running..."; sleep 5; done']

apiVersion: v1
kind: Pod
metadata:
  name: sandbox-pod
spec:
  runtimeClassName: runsc-sandbox
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Running..."; sleep 5; done']

A runtimeClass defines a runtime config. You can apply the runtimeClass to pods to male them use the sandboxed runtime. 

Name is the name used to apply the runtimeclass to pods. 

Handler refers to a section in the containerd config file that configure runsc. 


 k exec -it sandbox-pod -- dmesg
[   0.000000] Starting gVisor...
[   0.515402] Moving files to filing cabinet...
[   0.883028] Verifying that no non-zero bytes made their way into /dev/zero...
[   1.233888] Creating bureaucratic processes...
[   1.465186] Creating cloned children...
[   1.643854] Checking naughty and nice process list...
[   2.106130] Singleplexing /dev/ptmx...
[   2.147612] Creating process schedule...
[   2.300589] Feeding the init monster...
[   2.326012] Searching for socket adapter...
[   2.745690] Reading process obituaries...
[   2.983314] Setting up VFS...
[   3.146682] Setting up FUSE...
[   3.425243] Ready!

k exec -it non-sandbox-pod -- dmesg
[    0.000000] Linux version 5.4.0-105-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04)) #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 (Ubuntu 5.4.0-105.119-generic 5.4.174)
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.4.0-105-generic root=UUID=e98f1342-b444-420d-9329-24861832ef26 ro net.ifnames=0 biosdevname=0 nomodeset
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bffdbfff] usable
[    0.000000] BIOS-e820: [mem 0x00000000bffdc000-0x00000000bfffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000023fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.8 present.
[    0.000000] DMI: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.11.0-0-g63451fca13-prebuilt.qemu-project.org 04/01/2014
[    0.000000] Hypervisor detected: KVM
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr af801001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 527249198043 cycles
[    0.000014] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000026] tsc: Detected 2199.996 MHz processor
[    0.002606] e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
[    0.002609] e820: remove [mem 0x000a0000-0x000fffff] usable
[    0.002618] last_pfn = 0x240000 max_arch_pfn = 0x400000000
[    0.002663] MTRR default type: write-back
[    0.002671] MTRR fixed ranges enabled:
[    0.002673]   00000-9FFFF write-back
[    0.002674]   A0000-BFFFF uncachable
[    0.002675]   C0000-FFFFF write-protect
[    0.002676] MTRR variable ranges enabled:
[    0.002677]   0 base 00C0000000 mask FFC0000000 uncachable
[    0.002678]   1 disabled
[    0.002678]   2 disabled
[    0.002679]   3 disabled
[    0.002679]   4 disabled
[    0.002680]   5 disabled
[    0.002680]   6 disabled
[    0.002681]   7 disabled
[    0.002701] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT
[    0.002717] last_pfn = 0xbffdc max_arch_pfn = 0x400000000
